id: PBCC936F6
initial_creation_type: ocr
source_metadata:
  volumes:
    c4d19fa33c3c4790992e8919b10ddc15:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: དགེ་འདུན་རྗེས་སུ་དྲན་པའི་བཤད་པ།
      total_pages: 1498
      volume_number: 65
